### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by raianazaman** [raianazaman/project#4]
# Tasks
- [ ] start HTML and CSS
- [ ] the layout of the website
- [ ] color theme
- [ ] make it user-friendly
