### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by Samuel7532** [raianazaman/project#5]
# Tasks
- [ ] Create logic and functionality in application
- [ ] write out questions/filters to uncover users needs
- [ ] come up with better project name
